name: Action2 Test Windows

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ARM64
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.5"]
        architecture: ["arm64"]

    timeout-minutes: 30

    name: Action2 Python ${{ matrix.python-version }} ${{ matrix.architecture }}

    steps:
    - name: Checkout action-test
      uses: actions/checkout@v3
      
    - name: Echo
      run: |
          echo "Running in Powershell"

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    
    - name: install arm64 python
      run: nuget install pythonarm64 -Version ${{ matrix.python-version }} -OutputDirectory .

    - name: Python print
      run: |
        .\pythonarm64.${{ matrix.python-version }}\tools\python.exe -c "print('Running python on Action2')"

  success:
    permissions:
      contents: none
    needs: build
    runs-on: ubuntu-latest
    name: Windows Test Successful
    steps:
      - name: Success
        run: echo Windows Test Successful
